### PR TITLE
Add sources to npm package

### LINKED ISSUE #33: stylis-plugin-rtl + source-map-loader = breakage
The built source files and the sourcemaps of the library contains reference to the src/ directory:
```
{"version":3,"file":"stylis-rtl.js","sourceRoot":"","sources":["../src/stylis-rtl.ts"],"names":[]
```
But the actual src directory is not  shipped with the package, thus `../src/stylis-rtl.ts` does not exist.
When using source-map-loader ( as with create react app 5),  the build fails as it can't file `stylis-rtl.ts`

Possible solutions:
- Use inline source-maps 
- Don't generate source-maps 
- ship src as well

### LINKED ISSUE #34: stylis-plugin-rtl cause malfanction in component
this is error in my npm report:
WARNING in ./node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/hamid/Desktop/zahra-wieb-shop/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts' file: Error: ENOENT: no such file or directory, open '/home/hamid/Desktop/zahra-wieb-shop/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts'
 @ ./src/index.js 8:0-42 15:18-27

### LINKED ISSUE #35: Source-map file not found
I get this warning during Webpack build:

```bash
WARNING in ./node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '...\node_modules\stylis-plugin-rtl\src\stylis-rtl.ts' file: Error: ENOENT: no such file or directory, open '...\node_modules\stylis-plugin-rtl\src\stylis
-rtl.ts'
```

It expects to find the source-map file in the **`src` folder**. But it hasn't been published on NPM.

https://unpkg.com/browse/stylis-plugin-rtl@2.1.1/
image

***

I use `webpack@5.62.2`.

### PR DESCRIPTION
**Pull request by SurfaceS**
This PR add sources to the npm package.

According to the npm doc :
> If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.

So this file should be left empty.

Fix #35
Fix #34
Fix #33

### CODE REVIEW

**Comment by heinburger** [comment]
Hello! Can this please be merged? It would help a lot since I'm constantly trying to look away from this warning message/error

**Comment by vinothvkr** [comment]
Please somebody merge this request. This will fix the warning message. @probablyup

**Comment by boukmi** [comment]
Hello,
Can somebody merge this PR please? This will fix the warning issue.

Thank you

**Comment by oliviertassinari** [comment]
The solution proposed looks backward to me. I think that the problem is more with https://unpkg.com/stylis-plugin-rtl@2.1.1/dist/cjs/stylis-rtl.js. Why is there source maps in the first place?

```
//# sourceMappingURL=stylis-rtl.js.map
```

**Comment by magrinj** [comment]
If anyone want to fix it temporarily, you can use `patch-package` with the following patch:

```patch
diff --git a/node_modules/stylis-plugin-rtl/.DS_Store b/node_modules/stylis-plugin-rtl/.DS_Store
new file mode 100644
index 0000000..e69de29
diff --git a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts
index e3efd93..ac86e86 100644
--- a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts
+++ b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts
@@ -1,5 +1,5 @@
 import { Middleware } from 'stylis';
-declare type MiddlewareParams = Parameters<Middleware>;
+type MiddlewareParams = Parameters<Middleware>;
 declare function stylisRTLPlugin(element: MiddlewareParams[0], index: MiddlewareParams[1], children: MiddlewareParams[2], callback: MiddlewareParams[3]): string | void;
 export default stylisRTLPlugin;
 //# sourceMappingURL=stylis-rtl.d.ts.map
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts.map b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts.map
index 3edea57..e50c55a 100644
--- a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts.map
+++ b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.d.ts.map
@@ -1 +1 @@
-{"version":3,"file":"stylis-rtl.d.ts","sourceRoot":"","sources":["../../src/stylis-rtl.ts"],"names":[],"mappings":"AACA,OAAO,EAQL,UAAU,EAIX,MAAM,QAAQ,CAAC;AAEhB,aAAK,gBAAgB,GAAG,UAAU,CAAC,UAAU,CAAC,CAAC;AA4B/C,iBAAS,eAAe,CACtB,OAAO,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC5B,KAAK,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC1B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC7B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,GAC5B,MAAM,GAAG,IAAI,CAWf;AAMD,eAAe,eAAe,CAAC"}
\ No newline at end of file
+{"version":3,"file":"stylis-rtl.d.ts","sourceRoot":"","sources":["../../src/stylis-rtl.ts"],"names":[],"mappings":"AACA,OAAO,EAQL,UAAU,EAIX,MAAM,QAAQ,CAAC;AAEhB,KAAK,gBAAgB,GAAG,UAAU,CAAC,UAAU,CAAC,CAAC;AA4B/C,iBAAS,eAAe,CACtB,OAAO,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC5B,KAAK,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC1B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC7B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,GAC5B,MAAM,GAAG,IAAI,CAYf;AAMD,eAAe,eAAe,CAAC"}
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js
index 7eeb3d3..33b6846 100644
--- a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js
+++ b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js
@@ -37,4 +37,3 @@ function stylisRTLPlugin(element, index, children, callback) {
 // is unused
 Object.defineProperty(stylisRTLPlugin, 'name', { value: 'stylisRTLPlugin' });
 exports.default = stylisRTLPlugin;
-//# sourceMappingURL=stylis-rtl.js.map
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js.map b/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js.map
deleted file mode 100644
index 0af053c..0000000
--- a/node_modules/stylis-plugin-rtl/dist/cjs/stylis-rtl.js.map
+++ /dev/null
@@ -1 +0,0 @@
-{"version":3,"file":"stylis-rtl.js","sourceRoot":"","sources":["../../src/stylis-rtl.ts"],"names":[],"mappings":";;;;;AAAA,sDAAgC;AAChC,iCAYgB;AAIhB,SAAS,yBAAyB,CAChC,OAA4B,EAC5B,KAA0B,EAC1B,QAA6B;IAE7B,QAAQ,OAAO,CAAC,IAAI,EAAE;QACpB,KAAK,eAAM,CAAC;QACZ,KAAK,oBAAW,CAAC;QACjB,KAAK,gBAAO;YACV,OAAO,CAAC,OAAO,CAAC,MAAM,GAAG,OAAO,CAAC,MAAM,IAAI,OAAO,CAAC,KAAK,CAAC,CAAC;QAC5D,KAAK,gBAAO,CAAC,CAAC;YACZ,OAAO,CAAC,KAAK,GAAG,KAAK,CAAC,OAAO,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,KAAK,CAAC,IAAI,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,KAAK,CAAC;YAEvF,IAAI,KAAK,CAAC,OAAO,CAAC,OAAO,CAAC,QAAQ,CAAC,EAAE;gBACnC,OAAO,CAAC,QAAQ,CAAC,OAAO,CAAC,UAAC,CAAC;oBACzB,IAAI,CAAC,CAAC,IAAI,KAAK,gBAAO;wBAAE,CAAC,CAAC,QAAQ,GAAG,CAAC,CAAC,KAAK,CAAC;gBAC/C,CAAC,CAAC,CAAC;aACJ;SACF;KACF;IAED,IAAM,kBAAkB,GAAG,IAAA,kBAAS,EAAC,KAAK,CAAC,SAAS,CAAC,MAAM,CAAC,OAAO,CAAC,QAAQ,CAAC,EAAE,yBAAyB,CAAC,CAAC;IAE1G,OAAO,IAAA,eAAM,EAAC,kBAAkB,CAAC,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,MAAM,GAAG,OAAO,CAAC,KAAK,GAAG,GAAG,GAAG,kBAAkB,GAAG,GAAG,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC;AAC7G,CAAC;AAED,SAAS,eAAe,CACtB,OAA4B,EAC5B,KAA0B,EAC1B,QAA6B,EAC7B,QAA6B;IAE7B,IACE,OAAO,CAAC,IAAI,KAAK,kBAAS;QAC1B,OAAO,CAAC,IAAI,KAAK,iBAAQ;QACzB,CAAC,OAAO,CAAC,IAAI,KAAK,gBAAO,IAAI,CAAC,CAAC,OAAO,CAAC,MAAM,IAAI,OAAO,CAAC,MAAM,CAAC,IAAI,KAAK,cAAK,IAAI,OAAO,CAAC,MAAM,CAAC,IAAI,KAAK,gBAAO,CAAC,CAAC,EACnH;QACA,IAAM,WAAW,GAAG,kBAAQ,CAAC,SAAS,CAAC,yBAAyB,CAAC,OAAO,EAAE,KAAK,EAAE,QAAQ,CAAC,CAAC,CAAC;QAC5F,OAAO,CAAC,QAAQ,GAAG,WAAW,CAAC,CAAC,CAAC,IAAA,gBAAO,EAAC,WAAW,CAAC,CAAC,CAAC,CAAC,CAAC,QAAQ,CAAC,CAAC,CAAC,EAAE,CAAC;QAEvE,OAAO,CAAC,MAAM,GAAG,EAAE,CAAC;KACrB;AACH,CAAC;AAED,qFAAqF;AACrF,YAAY;AACZ,MAAM,CAAC,cAAc,CAAC,eAAe,EAAE,MAAM,EAAE,EAAE,KAAK,EAAE,iBAAiB,EAAE,CAAC,CAAC;AAE7E,kBAAe,eAAe,CAAC"}
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts
index e3efd93..ac86e86 100644
--- a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts
+++ b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts
@@ -1,5 +1,5 @@
 import { Middleware } from 'stylis';
-declare type MiddlewareParams = Parameters<Middleware>;
+type MiddlewareParams = Parameters<Middleware>;
 declare function stylisRTLPlugin(element: MiddlewareParams[0], index: MiddlewareParams[1], children: MiddlewareParams[2], callback: MiddlewareParams[3]): string | void;
 export default stylisRTLPlugin;
 //# sourceMappingURL=stylis-rtl.d.ts.map
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts.map b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts.map
index f091310..1d49d45 100644
--- a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts.map
+++ b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.d.ts.map
@@ -1 +1 @@
-{"version":3,"file":"stylis-rtl.d.ts","sourceRoot":"","sources":["../src/stylis-rtl.ts"],"names":[],"mappings":"AACA,OAAO,EAQL,UAAU,EAIX,MAAM,QAAQ,CAAC;AAEhB,aAAK,gBAAgB,GAAG,UAAU,CAAC,UAAU,CAAC,CAAC;AA4B/C,iBAAS,eAAe,CACtB,OAAO,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC5B,KAAK,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC1B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC7B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,GAC5B,MAAM,GAAG,IAAI,CAWf;AAMD,eAAe,eAAe,CAAC"}
\ No newline at end of file
+{"version":3,"file":"stylis-rtl.d.ts","sourceRoot":"","sources":["../src/stylis-rtl.ts"],"names":[],"mappings":"AACA,OAAO,EAQL,UAAU,EAIX,MAAM,QAAQ,CAAC;AAEhB,KAAK,gBAAgB,GAAG,UAAU,CAAC,UAAU,CAAC,CAAC;AA4B/C,iBAAS,eAAe,CACtB,OAAO,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC5B,KAAK,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC1B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,EAC7B,QAAQ,EAAE,gBAAgB,CAAC,CAAC,CAAC,GAC5B,MAAM,GAAG,IAAI,CAYf;AAMD,eAAe,eAAe,CAAC"}
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
index 513e600..3e341c3 100644
--- a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
+++ b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js
@@ -32,4 +32,3 @@ function stylisRTLPlugin(element, index, children, callback) {
 // is unused
 Object.defineProperty(stylisRTLPlugin, 'name', { value: 'stylisRTLPlugin' });
 export default stylisRTLPlugin;
-//# sourceMappingURL=stylis-rtl.js.map
\ No newline at end of file
diff --git a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js.map b/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js.map
deleted file mode 100644
index e6561ca..0000000
--- a/node_modules/stylis-plugin-rtl/dist/stylis-rtl.js.map
+++ /dev/null
@@ -1 +0,0 @@
-{"version":3,"file":"stylis-rtl.js","sourceRoot":"","sources":["../src/stylis-rtl.ts"],"names":[],"mappings":"AAAA,OAAO,QAAQ,MAAM,UAAU,CAAC;AAChC,OAAO,EACL,OAAO,EACP,OAAO,EACP,WAAW,EACX,MAAM,EACN,OAAO,EACP,SAAS,EACT,MAAM,EAEN,SAAS,EACT,KAAK,EACL,QAAQ,GACT,MAAM,QAAQ,CAAC;AAIhB,SAAS,yBAAyB,CAChC,OAA4B,EAC5B,KAA0B,EAC1B,QAA6B;IAE7B,QAAQ,OAAO,CAAC,IAAI,EAAE;QACpB,KAAK,MAAM,CAAC;QACZ,KAAK,WAAW,CAAC;QACjB,KAAK,OAAO;YACV,OAAO,CAAC,OAAO,CAAC,MAAM,GAAG,OAAO,CAAC,MAAM,IAAI,OAAO,CAAC,KAAK,CAAC,CAAC;QAC5D,KAAK,OAAO,CAAC,CAAC;YACZ,OAAO,CAAC,KAAK,GAAG,KAAK,CAAC,OAAO,CAAC,OAAO,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,KAAK,CAAC,IAAI,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,KAAK,CAAC;YAEvF,IAAI,KAAK,CAAC,OAAO,CAAC,OAAO,CAAC,QAAQ,CAAC,EAAE;gBACnC,OAAO,CAAC,QAAQ,CAAC,OAAO,CAAC,UAAC,CAAC;oBACzB,IAAI,CAAC,CAAC,IAAI,KAAK,OAAO;wBAAE,CAAC,CAAC,QAAQ,GAAG,CAAC,CAAC,KAAK,CAAC;gBAC/C,CAAC,CAAC,CAAC;aACJ;SACF;KACF;IAED,IAAM,kBAAkB,GAAG,SAAS,CAAC,KAAK,CAAC,SAAS,CAAC,MAAM,CAAC,OAAO,CAAC,QAAQ,CAAC,EAAE,yBAAyB,CAAC,CAAC;IAE1G,OAAO,MAAM,CAAC,kBAAkB,CAAC,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,MAAM,GAAG,OAAO,CAAC,KAAK,GAAG,GAAG,GAAG,kBAAkB,GAAG,GAAG,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC;AAC7G,CAAC;AAED,SAAS,eAAe,CACtB,OAA4B,EAC5B,KAA0B,EAC1B,QAA6B,EAC7B,QAA6B;IAE7B,IACE,OAAO,CAAC,IAAI,KAAK,SAAS;QAC1B,OAAO,CAAC,IAAI,KAAK,QAAQ;QACzB,CAAC,OAAO,CAAC,IAAI,KAAK,OAAO,IAAI,CAAC,CAAC,OAAO,CAAC,MAAM,IAAI,OAAO,CAAC,MAAM,CAAC,IAAI,KAAK,KAAK,IAAI,OAAO,CAAC,MAAM,CAAC,IAAI,KAAK,OAAO,CAAC,CAAC,EACnH;QACA,IAAM,WAAW,GAAG,QAAQ,CAAC,SAAS,CAAC,yBAAyB,CAAC,OAAO,EAAE,KAAK,EAAE,QAAQ,CAAC,CAAC,CAAC;QAC5F,OAAO,CAAC,QAAQ,GAAG,WAAW,CAAC,CAAC,CAAC,OAAO,CAAC,WAAW,CAAC,CAAC,CAAC,CAAC,CAAC,QAAQ,CAAC,CAAC,CAAC,EAAE,CAAC;QAEvE,OAAO,CAAC,MAAM,GAAG,EAAE,CAAC;KACrB;AACH,CAAC;AAED,qFAAqF;AACrF,YAAY;AACZ,MAAM,CAAC,cAAc,CAAC,eAAe,EAAE,MAAM,EAAE,EAAE,KAAK,EAAE,iBAAiB,EAAE,CAAC,CAAC;AAE7E,eAAe,eAAe,CAAC"}
\ No newline at end of file
```

**Review by ashishmisal23 — COMMENTED** [review]
Corrected & code Worked

**Pull request closed without merging**
